### ISSUE TITLE
[JS] Missing support for _metadata

### ISSUE THREAD

**Issue by vavido** [eclipse/ditto-clients#115]
As the title implies, the js client is currently lacking support for the `_metadta` fields. 

I am working on a PR to resolve this, but I am currently not 100% sure about the structure of the _metadata field and couldn't find any resource on it. 
My working assumption is that _metadata only contains a `features` property that is structured like the `features` property of a thing. Is this correct or can there be additional fields inside the `_metadata` property of a thing?

I'd be great if someone could clarify that for me or point me to a complete description of the ditto schema if one exists!

**Comment by vavido** [comment]
This is also somewhat related to #114, as this feature could also benefit from a simplified/tiedied model structure

**Comment by ffendt** [comment]
Hi @vavido,
afaik the `_metadata` field has the same structure as a `Thing` and could thus also include `attributes`. It should probably be possible to technically reuse the `Thing` model, but I'm not sure if this is desirable or not.

**Comment by vavido** [comment]
Hello @ffendt,
thanks for the help! 
One reason to not reuse the thing model for metadata is that it would also include the `_revision` and `_modified` fields, which don't appear inside the `_metadata` if I'm not mistaken, as well as a recursive `_metadata` field.

On the other hand, creating a reduced thing model just to remove these attributs could get a bit redundant. Maybe we should use a `Pick<>` type (https://www.typescriptlang.org/docs/handbook/utility-types.html#picktype-keys) for this?
