### ISSUE TITLE
[JS] CORS error in Firefox when POST is answered with redirect

### ISSUE THREAD

**Issue by vavido** [eclipse/ditto-clients#119]
Hello everyone, 
yesterday I encountered a strange bug where the HTTP POST request for sending a message to a feature. 

The initial request is 
```HTTP
POST /cloakedapi/2/things/c0001:CE6C2B4F3681A948/features/GridFlowTemperature/inbox/messages/history HTTP/1.1
Host: twin.othermo.de
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0
Accept: */*
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
authorization: Bearer <token>
content-type: application/json
Origin: https://localhost
Content-Length: 182
Connection: keep-alive
```

Which is answered with a `HTTP 303` redirect as follows:
```HTTP
HTTP/2 303 See Other
access-control-allow-credentials: true
access-control-allow-headers: Accept,Authorization,Cache-Control,Content-Type,Content-Length,DNT,If-Match,If-Modified-Since,If-None-Match,Keep-Alive,Origin,User-Agent,X-Requested-With
access-control-allow-methods: GET, POST, PUT, DELETE, OPTIONS
access-control-allow-origin: https://localhost
content-type: application/json
correlation-id: c225de5f-88eb-49e9-b64d-fd27e8f560b0
date: Wed, 13 Jan 2021 10:36:14 GMT
location: https://proxy.domain/c9239733-313b-4759-a3bf-39c47ab0338a
referrer-policy: no-referrer
response-required: false
server: nginx/1.13.12
vary: Accept-Encoding
version: 2
content-length: 2
X-Firefox-Spdy: h2
```

Firefox now prints a warning in the console that CORS Allow-Origin and Origin do not match, even though they are the exact same string.
![grafik](https://user-images.githubusercontent.com/7227663/104456136-876f0a00-55a8-11eb-8df3-5e8b89f49eb7.png)

Firefox even follows the redirect, and the pre-flight request for the next domain works, but for the actual `GET` of the URL, the same error occurs. The request promise is rejected and the request appears to be failed to the client.

After some digging, this appears to be a bug in the Firefox `fetch` implementation, because:
- The exact same code works in Chrome & Edge
- The exact same request worked before through axios which I believe uses XHR
- In current Firefox nightly and dev builds, the code works

There are even bugs in the Firefox Bugzilla describing this problem: 
- https://bugzilla.mozilla.org/show_bug.cgi?id=1444278
- https://bugzilla.mozilla.org/show_bug.cgi?id=1482309

Now the question is wether it is worth investing time and effort into a fix for this problem. 

Contra:
- This bug is quite niche, it seems to only happen
  - for POST requests that are answered with a redirect
  - In one specific browser with a rather small market share
- It seems to be fixed in Firefox 85, which is going to be released in about 14 days

Pro:
- This behavior seems to be present in firefox since atleast version 58. 
- The error will still be present for people using an older verion of Firefox 
- There might be other cases where CORS break requests that I just haven't discovered yet.

**Comment by ffendt** [comment]
Hi @vavido,

is this really related to Ditto (or Ditto clients), or is this rather related to the used nginx configuration?

**Comment by vavido** [comment]
Hi @ffendt, 
I'm confident the nginx config used here is not to blame, as requests to the same server used to work flawlessly when executed via Axios which uses XmlHttpRequest internally. Furthermore, the same code works in other (chrome-based) browsers and even the Firefox 85.0b9

**Comment by ffendt** [comment]
Hi @vavido,
so maybe to answer your initial question: No, I don't think this is worth investing. As you mentioned this is quite niche and a fixed version will be released soon.
If this is a blocker issue, it should be quite easy to implement `HttpRequester` with e.g. Axios to work around this bug until the new Firefox version is released.

**Comment by vavido** [comment]
Allright, that's what I thought too, I just wanted to hear a second opinion on the matter.
Maybe I will look into implementing a custom requester for the time beeing.

@ffendt I guess we can close this issue then, or should we leave it open in case anyone runs into the same issue in the future?

**Comment by ffendt** [comment]
We can close this for now and can reopen if needed.

**Comment by vavido** [comment]
It seems that the error is back in Firefox 87.0
However, I managed to work around this issue with the following `HttpRequester`: 

```typescript
class XhrRequester implements HttpRequester {
  async doRequest(
    method: string,
    url: string,
    header: Map<string, string>,
    body: string
  ): Promise<GenericResponse> {
    const config: AxiosRequestConfig = {
      method: method as Method,
      url: url,
      data: body,
      headers: Object.fromEntries(header),
    }

    const axiosResponse: AxiosResponse<any> = await axios(config)
    return {
      status: axiosResponse.status,
      headers: new Map(Object.entries(axiosResponse.headers)),
      body: axiosResponse.data,
    }
  }
}
```
So I don't think there's much need to fix this in the client
