### ISSUE TITLE
Release latest build on npm

### ISSUE THREAD

**Issue by tobias-zeptio** [eclipse/ditto-clients#122]
When I look in the npm repository the latest release is from 8 months ago, are these build not going to npm? How do I get a hold of build in that case?

**Comment by ffendt** [comment]
Hi @tobias-zeptio,
we're currently only publishing final releases for Ditto and its clients. For the JS client our plan was to release a 3.0.0 after #117 gets merged.
Are you in need of some in-between milestone releases? Would you need only milestones of the JavaScript client or also of Ditto or the Java client?

**Comment by tobias-zeptio** [comment]
I'm specifically after the PR [208](https://github.com/eclipse/ditto-clients/pull/108), to be able to use JWT token with the DOM client..

**Comment by ffendt** [comment]
Oh, I think we forgot to publish a bugfix release after your PR, sorry. Would it be ok for you, if we'd publish your changes together with the breaking changes of 3.0.0 (see #121)? I could try to publish it as a 2.0.1 otherwise.

**Comment by tobias-zeptio** [comment]
I'd appreciate if it's released as 2.0.1 as soon as possible, since I depend on that change to move forward. But it depends on when 3.0.0 is released.

**Comment by ffendt** [comment]
Hi @tobias-zeptio,

I published a 2.1.0 just now containing #108 and #95.

Thank you again for pinging us on the release.
