### ISSUE TITLE
[JS]: Thing is missing the definition field

### ISSUE THREAD

**Issue by vhdirk** [eclipse/ditto-clients#127]
It is returned in the response, but it is never mapped.

**Comment by AhwiniMirajkar** [comment]
I'm new to open source contribution 
Could u help me

**Comment by ffendt** [comment]
Hi @AhwiniMirajkar,
there is already a Pull Request that is almost finished: #126.
You can have a look at [CONTRIBUTING.md](https://github.com/eclipse/ditto-clients/blob/master/CONTRIBUTING.md) for information on how to contribute to the Eclipse Ditto clients project.
