### ISSUE TITLE
The websocket session expired because the JWT used for authentication has expired

### ISSUE THREAD

**Issue by wklenk** [eclipse/ditto-clients#30]
Im am using ditto-client 1.0.0-M3 and OAuth based authentication (client-id, client-secret). 
I open a websocket connection to get notified about twin events.
Every 60 minutes, I get the following message:

> 2019-11-10T09:04:43.028+01:00 Client <e68d7238-32bb-444f-9bd6-dc04dd7e1433:1db28b98-2e94-4b83-a5ef-65580566e28f>: Reconnection is enabled. Reconnecting in <5> seconds ...
> 2019-11-10T09:04:43.028+01:00 Client <e68d7238-32bb-444f-9bd6-dc04dd7e1433:1db28b98-2e94-4b83-a5ef-65580566e28f>: WebSocket connection to endpoint <wss://things.eu-1.bosch-iot-suite.com/ws/1> was closed by Server with code <1000> and reason <null>.
> 2019-11-10T09:04:43.028+01:00 Client <e68d7238-32bb-444f-9bd6-dc04dd7e1433:1db28b98-2e94-4b83-a5ef-65580566e28f>: Got TWIN ThingErrorResponse: <GatewayWebsocketSessionExpiredException: The websocket session expired because the JWT used for authentication has expired. - You need to periodically refresh your websocket session with a new JWT.>
> 2019-11-10T09:04:48.029+01:00 Recreating Websocket..
> 2019-11-10T09:04:48.290+01:00 Connecting WebSocket on endpoint <wss://things.eu-1.bosch-iot-suite.com/ws/1>
> 2019-11-10T09:04:48.505+01:00 Client <e68d7238-32bb-444f-9bd6-dc04dd7e1433:1db28b98-2e94-4b83-a5ef-65580566e28f>: WebSocket connection is established
> 2019-11-10T09:04:48.506+01:00 Client <e68d7238-32bb-444f-9bd6-dc04dd7e1433:1db28b98-2e94-4b83-a5ef-65580566e28f>: Requesting at backend that this client wants to <START-SEND-EVENTS> with params <{}>
> 2019-11-10T09:04:48.506+01:00 Client <e68d7238-32bb-444f-9bd6-dc04dd7e1433:1db28b98-2e94-4b83-a5ef-65580566e28f>: Subscribing again for messages from backend after reconnection

While this is not a big issue, as the ditto-client reconnects automatically after 5 seconds, there is still the risk that I loose incoming events within this 5 seconds interval.
Are there plans to implement the "refreshing" of the JWT ?

**Comment by jokraehe** [comment]
Hi @wklenk 
there is in fact a refresh mechanism in place for client credentials authentication. It should automatically get a new access token from your configured authorization server and send it to the Ditto backend. I'll try to reproduce and get back to you.
