### ISSUE TITLE
Add support for top-level policy management

### ISSUE THREAD

**Issue by dguggemos** [eclipse/ditto-clients#31]
With eclipse/ditto#554 policies are supported in the ditto protocol. The Ditto Java Client will also be extended to support top-level policy management. I.e. there will be no no Java API to manipulate subjects/entries, but only the whole policy (nevertheless the respective subject/entry commands can be built using the ProcotolAdapter directly).

**Comment by thjaeckle** [comment]
Closed by PR #46
