### ISSUE TITLE
Add support in Java client for notification/monitoring of connection problems

### ISSUE THREAD

**Issue by geglock** [eclipse/ditto-clients#39]
The Java client establishes a WebSocket connection to the Ditto back end and automatically re-connects this connection in case of problems. This is fine, but it is done invisible to my application that uses the client. This means, that my application cannot monitor such connection problems and alert if they are critical. During re-connects some (optionally) important thing events could also be missed.

It would be good to have a possibility to configure a callback/event handler to get informed about such connectivity problems - even so they are compensated by automatic re-connects.

**Comment by thjaeckle** [comment]
Don't we have this kind of hook now @Yannic92 ?

**Comment by Yannic92** [comment]
https://github.com/eclipse/ditto-clients/pull/75

This should be exactly what's requested by this issue.

**Comment by thjaeckle** [comment]
Good, then closing this issue via #75
