### ISSUE TITLE
[JS] putThing throws error when updating an existing Thing

### ISSUE THREAD

**Issue by vhdirk** [eclipse/ditto-clients#61]
According to the docs, a `PUT` request for an existing `Thing` will have ditto respond with status 204 and an empty body.
The JS client SDK, however, always expects body: https://github.com/eclipse/ditto-clients/blob/master/javascript/lib/api/src/client/request-factory/request-sender.ts#L48

**Comment by ffendt** [comment]
Good catch! Do you want to provide a PR for that?
