### ISSUE TITLE
Client always connecting on localhost

### ISSUE THREAD

**Issue by bialad** [eclipse/ditto-clients#93]
I'm trying to connect to a ditto instance running on another host with this configuration.

```    
        const httpClient = DittoNodeClient
            .newHttpClient()
            .withTls()
            .withDomain(this.domain)
            .withAuthProvider(NodeHttpBasicAuth.newInstance(this.username, this.password))
            .apiVersion2()
            .build();

        const thingsHandle = httpClient.getThingsHandle();

        thingsHandle.getThing('org.example:device_1')
            .then(returnedThing => {
                console.log(`Get returned ${JSON.stringify(returnedThing)}`);
            })
            .catch((err) => {
                console.log('error', err);
            });
```
suing this library version

```
    "@eclipse-ditto/ditto-javascript-client-api_1.0": "^2.0.0",
    "@eclipse-ditto/ditto-javascript-client-node_1.0": "^2.0.0",
```

But I get this error

`Error: connect ECONNREFUSED 127.0.0.1:80`

It seems it's connecting to localhost even though domain is set.

**Comment by thjaeckle** [comment]
That's really strange as we don't have a default of `localhost` and port `80` in the codebase.

* Are you behind a HTTP proxy?
* Did you try using the `DittoNodeClient.newWebSocketClient()` and have the same issue?

**Comment by bialad** [comment]
No proxy, and withTls is set so I guess port should be 443.

Websockets is the same.

**Comment by bialad** [comment]
If I console.log thingsHandle I get this:

```
DefaultThingsHandle {
  requestFactory: HttpRequestSender {
    requester: NodeRequester { proxyAgent: [HttpsProxyAgent] },
    baseUrl: ImmutableURL {
      protocol: 'https',
      domain: 'ditto.example.com',
      path: '/api/2/things',
      queryParams: []
    },
    authenticationProviders: [ [NodeHttpBasicAuth] ]
  }
}
```

**Comment by bialad** [comment]
If I enter the domain in my browser I get the ditto landing page, so it should work.

**Comment by thjaeckle** [comment]
Did you try specifying the port explicitly in the `domain`, so e.g.: `ditto.example.com:443`?

**Comment by bialad** [comment]
No difference when adding the port.

**Comment by bialad** [comment]
I mapped my local port 80 to the remote host, and now I get an html error. I assume it using the base url, and getting the landing page back.

Seems like the client is not actually constructing the url through RequestSender.fetchRequest() and RequestSender.buildUrl()

**Comment by bialad** [comment]
f I run `console.log(thingsHandle.requestFactory.buildUrl())` I get `https://ditto.example.com/api/2/things`

**Comment by thjaeckle** [comment]
I just verified on https://repl.it/repls/UnlawfulProfitableGlitches#index.js

with:
```javascript
const ditto = require('@eclipse-ditto/ditto-javascript-client-node_1.0');
const d = require('@eclipse-ditto/ditto-javascript-client-api_1.0');

const domain = 'ditto.eclipse.org';
const username = 'ditto';
const password = 'ditto';

// could also use newWebSocketClient() for the WebSocket implementation
const client = ditto.DittoNodeClient.newHttpClient()
  .withTls()
  .withDomain(domain)
  .withAuthProvider(ditto.NodeHttpBasicAuth.newInstance(username, password))
  .apiVersion2()
  .build();

const thingsHandle = client.getThingsHandle();
const thing = new d.Thing('the:thing');
thingsHandle.putThing(thing)
  .then(result => console.log(`Finished putting thing with result: ${JSON.stringify(result)}`));
```

With the same result:
```
(node:160) UnhandledPromiseRejectionWarning: Error: Error: connect ECONNREFUSED 127.0.0.1:80
    at ClientRequest.<anonymous> (/home/runner/UnlawfulProfitableGlitches/node_modules/@eclipse-ditto/ditto-javascript-client-node_1.0/dist/node-http.js:67:27)
...
```

**Comment by bialad** [comment]
Oh good, than I can stop finding issues in my setup!

**Comment by thjaeckle** [comment]
Yeah, seems like either noone used this before and noticed or that because of some updated dependencies this stopped working.
I have no clue about JS, so I won't be of help in fixing this bug :(

**Comment by bialad** [comment]
OK, so I found the issue.

In the `node-library` file `node-http.ts` row `103` there is a `this.proxyAgent != undefined` check. Which it never is, even though no proxy is set. I changed it to `this.proxyAgent.options.path != undefined` which is set through `newHttpClient()`, and then it works.

This might not be the best way to handle it though, depending on the proxyAgent implementation. Do you know anyone who can comment on this?

**Comment by thjaeckle** [comment]
Cool, thx .. that will help a lot.
@joosdavid will have a look ..
